# Import sklearn classifiers 
from sklearn.ensemble._weight_boosting import AdaBoostClassifier
from sklearn.ensemble._bagging import BaggingClassifier
from sklearn.naive_bayes import BernoulliNB
from sklearn.calibration import CalibratedClassifierCV
from sklearn.naive_bayes import CategoricalNB
from sklearn.multioutput import ClassifierChain
from sklearn.naive_bayes import ComplementNB
from sklearn.tree._classes import DecisionTreeClassifier
from sklearn.dummy import DummyClassifier
from sklearn.tree._classes import ExtraTreeClassifier
from sklearn.ensemble._forest import ExtraTreesClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.gaussian_process._gpc import GaussianProcessClassifier
from sklearn.ensemble._gb import GradientBoostingClassifier
from sklearn.ensemble._hist_gradient_boosting.gradient_boosting import HistGradientBoostingClassifier
from sklearn.neighbors._classification import KNeighborsClassifier
from sklearn.semi_supervised._label_propagation import LabelPropagation
from sklearn.semi_supervised._label_propagation import LabelSpreading
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis
from sklearn.svm._classes import LinearSVC
from sklearn.linear_model._logistic import LogisticRegression
from sklearn.linear_model._logistic import LogisticRegressionCV
from sklearn.neural_network._multilayer_perceptron import MLPClassifier
from sklearn.multioutput import MultiOutputClassifier
from sklearn.naive_bayes import MultinomialNB
from sklearn.neighbors._nearest_centroid import NearestCentroid
from sklearn.svm._classes import NuSVC
from sklearn.multiclass import OneVsOneClassifier
from sklearn.multiclass import OneVsRestClassifier
from sklearn.multiclass import OutputCodeClassifier
from sklearn.linear_model._passive_aggressive import PassiveAggressiveClassifier
from sklearn.linear_model._perceptron import Perceptron
from sklearn.discriminant_analysis import QuadraticDiscriminantAnalysis
from sklearn.neighbors._classification import RadiusNeighborsClassifier
from sklearn.ensemble._forest import RandomForestClassifier
from sklearn.linear_model._ridge import RidgeClassifier
from sklearn.linear_model._ridge import RidgeClassifierCV
from sklearn.linear_model._stochastic_gradient import SGDClassifier
from sklearn.svm._classes import SVC
from sklearn.ensemble._stacking import StackingClassifier
from sklearn.ensemble._voting import VotingClassifier

# Import sklearn regressors
from sklearn.linear_model._bayes import ARDRegression
from sklearn.ensemble._weight_boosting import AdaBoostRegressor  
from sklearn.ensemble._bagging import BaggingRegressor
from sklearn.linear_model._bayes import BayesianRidge
from sklearn.cross_decomposition._pls import CCA
from sklearn.tree._classes import DecisionTreeRegressor
from sklearn.dummy import DummyRegressor
from sklearn.linear_model._coordinate_descent import ElasticNet  
from sklearn.linear_model._coordinate_descent import ElasticNetCV
from sklearn.tree._classes import ExtraTreeRegressor
from sklearn.ensemble._forest import ExtraTreesRegressor
from sklearn.linear_model._glm.glm import GammaRegressor
from sklearn.gaussian_process._gpr import GaussianProcessRegressor
from sklearn.ensemble._gb import GradientBoostingRegressor
from sklearn.ensemble._hist_gradient_boosting.gradient_boosting import HistGradientBoostingRegressor
from sklearn.linear_model._huber import HuberRegressor
from sklearn.isotonic import IsotonicRegression
from sklearn.neighbors._regression import KNeighborsRegressor
from sklearn.kernel_ridge import KernelRidge
from sklearn.linear_model._least_angle import Lars
from sklearn.linear_model._least_angle import LarsCV
from sklearn.linear_model._coordinate_descent import Lasso
from sklearn.linear_model._coordinate_descent import LassoCV
from sklearn.linear_model._least_angle import LassoLars
from sklearn.linear_model._least_angle import LassoLarsCV
from sklearn.linear_model._least_angle import LassoLarsIC
from sklearn.linear_model._base import LinearRegression
from sklearn.svm._classes import LinearSVR
from sklearn.neural_network._multilayer_perceptron import MLPRegressor
from sklearn.multioutput import MultiOutputRegressor
from sklearn.linear_model._coordinate_descent import MultiTaskElasticNet
from sklearn.linear_model._coordinate_descent import MultiTaskElasticNetCV
from sklearn.linear_model._coordinate_descent import MultiTaskLasso
from sklearn.linear_model._coordinate_descent import MultiTaskLassoCV
from sklearn.svm._classes import NuSVR
from sklearn.linear_model._omp import OrthogonalMatchingPursuit
from sklearn.linear_model._omp import OrthogonalMatchingPursuitCV
from sklearn.cross_decomposition._pls import PLSCanonical
from sklearn.cross_decomposition._pls import PLSRegression
from sklearn.linear_model._passive_aggressive import PassiveAggressiveRegressor
from sklearn.linear_model._glm.glm import PoissonRegressor
from sklearn.linear_model._quantile import QuantileRegressor
from sklearn.linear_model._ransac import RANSACRegressor
from sklearn.neighbors._regression import RadiusNeighborsRegressor
from sklearn.ensemble._forest import RandomForestRegressor
from sklearn.multioutput import RegressorChain
from sklearn.linear_model._ridge import Ridge
from sklearn.linear_model._ridge import RidgeCV
from sklearn.linear_model._stochastic_gradient import SGDRegressor
from sklearn.svm._classes import SVR
from sklearn.ensemble._stacking import StackingRegressor
from sklearn.linear_model._theil_sen import TheilSenRegressor
from sklearn.compose._target import TransformedTargetRegressor
from sklearn.linear_model._glm.glm import TweedieRegressor
from sklearn.ensemble._voting import VotingRegressor